FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN addgroup --system app && adduser --system --group app
WORKDIR /app
RUN apt -get update && apt -get install --no -install recommends\
  build essential\
  libpq-dev\
  && rm -rf \var\lib\apt\lists*
COPY requirements.txt .
RUN pip install -upgrade pip \
  && pip install --no-cache-dir -r requirements.txt
COPY ..
RUN chown -R app:app \app
USER app
EXPOSE 8000
CMD["gunicorn", "app.main:app", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000" "--worker", "3"]
  
